name: release

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Version bump type
        options: 
        - patch
        - minor
        - major

jobs:
  build:
    name: Test on node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
        node-version: ${{ matrix.node-version }}
    - name: Install deps
      run: npm ci
    - name: Liniting
      run: npm run lint
    - name: Testing
      run: npm test
  
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          
    - name: Install deps
      run: npm ci          

    - name: Git configuration
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
                  
    - name: Bump release version
      run: |
        echo "NEW_VERSION=$(npm --no-git-tag-version version $RELEASE_TYPE)" >> $GITHUB_ENV
        echo "RELEASE_TAG=latest" >> $GITHUB_ENV
      env:
        RELEASE_TYPE: ${{ github.event.inputs.version }}
    
    - name: Update changelog
      uses: superfaceai/release-changelog-action@v1
      with:
        path-to-changelog: CHANGELOG.md
        version: ${{ env.NEW_VERSION }}
        operation: release
        
    - name: Commit CHANGELOG.md and package.json changes and create tag
      run: |
        git add "package.json"
        git add "CHANGELOG.md"
        git commit -m "chore: release ${{ env.NEW_VERSION }}"
        git tag ${{ env.NEW_VERSION }}        
        
    - name: Publish
      run: |
        npm run build
        npm publish --verbose --access public --tag ${{ env.RELEASE_TAG }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Push changes to repository
      run: |
        git push origin && git push --tags
