name: release

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Version bump type
        options: 
        - patch
        - minor
        - major

jobs:
  build:
    name: Test on node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
        node-version: ${{ matrix.node-version }}
    - name: Install deps
      run: npm ci
    - name: Liniting
      run: npm run lint
    - name: Testing
      run: npm test
  
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
    - name: Install deps
      run: npm ci
    - name: publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        npm set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
        npm run publish:np -- ${{ github.event.inputs.version }}