name: tests

on: 
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: Test on node ${{ matrix.node-version }}
    #runs-on: ubuntu-latest
    runs-on: gh-test
    strategy:
      fail-fast: true
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
        node-version: ${{ matrix.node-version }}
    - name: Install deps
      run: npm ci
    - name: Liniting
      run: npm run lint
    - name: Testing
      run: npm test
